version: "{build}"

platform: x64

branches:
  only:
    - master

clone_depth: 10

skip_tags: true

install:
  - ps: Install-Product node 6
  - npm run prepare
  - npm install
  - npm run lint
  - npm run test

build: off
test: off
deploy: off
